# Generated by Django 2.1.2 on 2019-04-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20190403_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comp_data',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_comp_data',
            name='is_arrendador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_comp_data',
            name='is_arrendatario',
            field=models.BooleanField(default=False),
        ),
    ]
