# Generated by Django 2.1.7 on 2019-04-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_rol_userrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_comp_data',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='user_comp_data',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user_comp_data',
            name='is_arrendador',
        ),
        migrations.RemoveField(
            model_name='user_comp_data',
            name='is_arrendatario',
        ),
    ]
