# Generated by Django 2.1.7 on 2019-04-04 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0008_auto_20190404_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrol',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='userrol',
            name='user',
        ),
        migrations.AddField(
            model_name='rol',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Userrol',
        ),
    ]
