# Generated by Django 2.1.7 on 2019-04-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_numverification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_comp_data',
            name='lat_last_login',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user_comp_data',
            name='lng_last_login',
            field=models.FloatField(null=True),
        ),
    ]
