# Generated by Django 2.1.7 on 2019-04-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0017_remove_user_comp_data_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='user',
        ),
    ]
