# Generated by Django 2.1.7 on 2019-05-21 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0026_estacionamiento_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='estrellas',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(default='mastercard', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion',
            name='estacionamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Estacionamiento'),
        ),
    ]
