# Generated by Django 2.1.7 on 2019-05-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0027_auto_20190521_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='estacionamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking.Estacionamiento'),
            preserve_default=False,
        ),
    ]
