# Generated by Django 2.1.7 on 2019-05-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0029_auto_20190525_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.TipoTarjeta'),
        ),
    ]
