# Generated by Django 2.1.7 on 2019-05-26 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0033_auto_20190525_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 25, 21, 59, 39, 485097)),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='time',
            field=models.BigIntegerField(null=True),
        ),
    ]
