# Generated by Django 2.1.7 on 2019-05-26 02:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0037_auto_20190525_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 2, 12, 2, 347426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 5, 26, 2, 12, 2, 350362, tzinfo=utc)),
        ),
    ]
