# Generated by Django 2.1.7 on 2019-04-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comp_data',
            name='rut',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
