# Generated by Django 2.1.2 on 2019-04-04 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0002_user_comp_data_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('ultimos_4_numeros', models.CharField(max_length=4)),
                ('fecha_expiracion', models.DateTimeField()),
                ('codigo_verificacion', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='arriendo',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='parking.Auto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_comp_data',
            name='ui_color_1',
            field=models.CharField(default=0, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_comp_data',
            name='ui_color_2',
            field=models.CharField(default=0, max_length=23),
            preserve_default=False,
        ),
    ]
