# Generated by Django 2.1.7 on 2019-04-04 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20190404_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Rol'),
        ),
        migrations.AlterField(
            model_name='userrol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
