# Generated by Django 2.1.7 on 2019-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_auto_20190416_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_comp_data',
            name='lat_last_login',
            field=models.FloatField(default='null', null=True),
        ),
        migrations.AlterField(
            model_name='user_comp_data',
            name='lng_last_login',
            field=models.FloatField(default='null', null=True),
        ),
        migrations.AlterField(
            model_name='user_comp_data',
            name='ui_color_1',
            field=models.CharField(default='rgb(98, 0, 238)', max_length=23),
        ),
        migrations.AlterField(
            model_name='user_comp_data',
            name='ui_color_2',
            field=models.CharField(default='rgb(255, 251, 0)', max_length=23),
        ),
    ]
