# Generated by Django 2.1.7 on 2019-04-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_user_comp_data_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_comp_data',
            name='ready',
        ),
    ]
