# Generated by Django 2.1.7 on 2019-04-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0020_auto_20190420_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
