# Generated by Django 2.1.7 on 2019-04-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0021_estacionamiento_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='on_use',
            field=models.BooleanField(default=False),
        ),
    ]
