# Generated by Django 2.1.7 on 2019-04-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0022_estacionamiento_on_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_comp_data',
            name='rut',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
