# Generated by Django 2.1.7 on 2019-05-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0024_region_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='geo',
        ),
        migrations.AddField(
            model_name='comuna',
            name='geo',
            field=models.FileField(null=True, upload_to='geo'),
        ),
    ]
