# Generated by Django 2.1.7 on 2019-05-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0025_auto_20190507_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
