# Generated by Django 2.1.7 on 2019-05-25 20:54

from django.db import migrations, models
import parking.models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0028_imagen_estacionamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='estrellas',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='image',
            field=models.ImageField(upload_to=parking.models.parking_directory_path),
        ),
    ]
