# Generated by Django 2.1.7 on 2019-06-10 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import parking.models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0039_auto_20190529_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comp_data',
            name='user_thumb',
            field=models.ImageField(default=0, upload_to=parking.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 5, 1, 50, 10328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 6, 10, 5, 1, 50, 14328, tzinfo=utc)),
        ),
    ]
